version: "2"

run:
  go: "1.24"
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - nilnil
    - revive
    - staticcheck
    - unconvert
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gosec:
      excludes:
        - G104
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - staticcheck
        text: 'SA9003:'
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
