
# GoReleaser configuration file
# Documentation at https://goreleaser.com
#
# Note: This project uses CGO (required by the audio library).
# Cross-compiling CGO code for macOS from Linux is complex and requires macOS SDK.
# This configuration only builds for Linux. macOS users can build from source.
#
# For local testing: goreleaser build --snapshot --clean --single-target
version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: bleep
    main: .
    binary: bleep
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: Gioni06
    name: bleep
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
