
# GoReleaser configuration file
# Documentation at https://goreleaser.com
#
# Multi-platform build configuration:
# - Linux: CGO enabled with Zig for cross-compilation (ALSA required)
# - Darwin/macOS: CGO disabled (oto/v3 doesn't require CGO on macOS)
#
# For local testing: goreleaser build --snapshot --clean --single-target
version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: bleep
    main: .
    binary: bleep
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Platform-specific overrides
    # Note: macOS (darwin) doesn't require CGO for oto/v3
    # Linux requires CGO for ALSA support
    ignore:
      # Skip Linux ARM64 - cross-compiling CGO with ALSA is complex
      # ARM64 Linux users can build from source with: go build
      - goos: linux
        goarch: arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=0
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: Gioni06
    name: bleep
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

aurs:
  - name: bleep-bin
    homepage: "https://github.com/Gioni06/bleep"
    description: "Interval timer with audio beep for productivity and Waybar integration"
    maintainers:
      - "Gioni06 <gioni06@users.noreply.github.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/bleep-bin.git"
    depends:
      - alsa-lib
    package: |-
      install -Dm755 "./bleep" "${pkgdir}/usr/bin/bleep"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/bleep/LICENSE"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
